# Generated by Django 4.1.1 on 2022-09-21 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.CharField(max_length=250)),
                ('knowledge', models.CharField(max_length=250)),
                ('manifesto', models.CharField(max_length=250)),
                ('globals', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
                ('total', models.CharField(max_length=250)),
                ('candidates_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_id', to='candidates.candidates')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
